// =================== Database Types ===================
// These will be auto-generated by Supabase CLI later.
// For now, define manually to match schema.sql.

export type UserRole = "organiser" | "member";
export type RSVPStatus = "confirmed" | "declined" | "pending" | "maybe";
export type ApplicationStatus = "pending" | "approved" | "rejected";
export type FileType = "document" | "image" | "audio";

// =================== Table Row Types ===================

export interface Profile {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface Event {
  id: string;
  name: string;
  date: string;
  start_time: string;
  end_time: string;
  venue: string;
  description: string;
  open_mic_enabled: boolean;
  slug: string;
  setlist_id: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface EventMember {
  id: string;
  event_id: string;
  user_id: string;
  event_role: string | null;
  rsvp: RSVPStatus;
  created_at: string;
  updated_at: string;
}

export interface Setlist {
  id: string;
  name: string;
  event_id: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface Song {
  id: string;
  setlist_id: string;
  name: string;
  key: string;
  bpm: number;
  arrangement_notes: string;
  is_open_mic: boolean;
  open_mic_application_id: string | null;
  position: number;
  created_at: string;
  updated_at: string;
}

export interface SongRoleAssignment {
  id: string;
  song_id: string;
  role: string;
  person_id: string;
  person_name: string;
  is_open_mic_performer: boolean;
  created_at: string;
}

export interface Announcement {
  id: string;
  title: string | null;
  body: string;
  author_id: string;
  created_at: string;
  updated_at: string;
}

export interface FileRecord {
  id: string;
  name: string;
  type: FileType;
  size: string;
  storage_path: string;
  uploader_id: string;
  event_id: string | null;
  created_at: string;
}

export interface OpenMicApplication {
  id: string;
  event_id: string;
  full_name: string;
  email: string;
  phone: string | null;
  song: string;
  instrument_needs: string;
  status: ApplicationStatus;
  organiser_notes: string | null;
  submitted_at: string;
  updated_at: string;
}

// =================== Composite Types (for JOINs) ===================

export type EventMemberWithProfile = EventMember & {
  profiles: Profile;
};

export type EventWithMembers = Event & {
  event_members: EventMemberWithProfile[];
};

export type SongWithRoles = Song & {
  song_role_assignments: SongRoleAssignment[];
};

export type SetlistWithSongs = Setlist & {
  songs: SongWithRoles[];
};

export type AnnouncementWithAuthor = Announcement & {
  profiles: Pick<Profile, "name" | "avatar_url">;
};

export type FileWithUploader = FileRecord & {
  profiles: Pick<Profile, "name">;
};

// =================== Database Type (Supabase generic) ===================
// Placeholder — will be replaced by `supabase gen types typescript` output

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: Omit<Profile, "created_at" | "updated_at">;
        Update: Partial<Omit<Profile, "id" | "created_at" | "updated_at">>;
      };
      events: {
        Row: Event;
        Insert: Omit<Event, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<Event, "id" | "created_at" | "updated_at">>;
      };
      event_members: {
        Row: EventMember;
        Insert: Omit<EventMember, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<EventMember, "id" | "created_at" | "updated_at">>;
      };
      setlists: {
        Row: Setlist;
        Insert: Omit<Setlist, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<Setlist, "id" | "created_at" | "updated_at">>;
      };
      songs: {
        Row: Song;
        Insert: Omit<Song, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<Song, "id" | "created_at" | "updated_at">>;
      };
      song_role_assignments: {
        Row: SongRoleAssignment;
        Insert: Omit<SongRoleAssignment, "id" | "created_at">;
        Update: Partial<Omit<SongRoleAssignment, "id" | "created_at">>;
      };
      announcements: {
        Row: Announcement;
        Insert: Omit<Announcement, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<Announcement, "id" | "created_at" | "updated_at">>;
      };
      files: {
        Row: FileRecord;
        Insert: Omit<FileRecord, "id" | "created_at">;
        Update: Partial<Omit<FileRecord, "id" | "created_at">>;
      };
      open_mic_applications: {
        Row: OpenMicApplication;
        Insert: Omit<OpenMicApplication, "id" | "submitted_at" | "updated_at">;
        Update: Partial<Omit<OpenMicApplication, "id" | "submitted_at" | "updated_at">>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      rsvp_status: RSVPStatus;
      application_status: ApplicationStatus;
      file_type: FileType;
    };
  };
}
